AllCops:
  Include:
    - "Gemfile"
    - "Guardfile"
    - "Rakefile"
    - "*.gemspec"
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Description: A calculated magnitude based on number of assignments, branches, and
    conditions.
  Max: 15
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*_spec.rb"

Metrics/BlockLength:
  Description: Avoid long blocks with many lines.
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*_spec.rb"

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Description: Avoid methods longer than 10 lines of code.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#short-methods
  CountComments: false
  Max: 10
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*_spec.rb"
